steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'dbt_poc/Dockerfile'
      - '-t'
      - 'europe-west2-docker.pkg.dev/sturdy-practice-245323/dbt-poc/dbt-bigquery:v1'
      - '.'

images:
  - 'europe-west2-docker.pkg.dev/sturdy-practice-245323/dbt-poc/dbt-bigquery:v1'

options:
  logging: CLOUD_LOGGING_ONLY